---
- name: Port check
  shell: /bin/netstat -tnlp | grep ":{{ item }} "
  register: port_list
  ignore_errors: true
  with_items:
  - "{{ kubernetes_ports }}"
- name: Print ports
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ port_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Health check API
  uri:
    url: https://localhost:6443/livez?verbose
    method: GET
    status_code: 200
    body_format: json
    return_content: yes
    validate_certs: no
  register: health_check_response
  ignore_errors: true
  
- name: Print health check response
  debug: 
    msg: "{{ health_check_response.content }}"

- name: Get a list of all nodes from any namespace
  command: "kubectl get nodes -o wide"
  register: node_list
  ignore_errors: true

- name: Print all nodes List
  debug: 
    msg: "{{ node_list.stdout_lines }}"

- name: Get a list of all pods from any namespace
  command: "kubectl get pods -A"
  register: pod_list
  ignore_errors: true

- name: Print all Pods List
  debug: 
    msg: "{{ pod_list.stdout_lines }}"

- name: Process check
  shell: ps aux | grep -v "grep" | grep {{ item }}
  with_items:
  - "{{ kubernetes_process }}"
  register: ps_list
  ignore_errors: true

- name: Print process
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items: 
  - "{{ ps_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Service status check
  shell: service {{ item }} status
  with_items:
  - "{{ kubernetes_services }}"
  register: service_list
  ignore_errors: true

- name: Print services status
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ service_list.results }}"
  loop_control:
    label: "{{ item.item }}"
