---
- name: Port check
  shell: /bin/netstat -tnlp | grep ":{{ item }} "
  register: port_list
  ignore_errors: true
  with_items:
  - "{{ maxscale_port }}"

- name: Print ports
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ port_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Process check
  shell: ps aux | grep -v "grep" | grep {{ item }}
  with_items:
  - "{{ maxscale_process }}"
  register: ps_list
  ignore_errors: true

- name: Print process
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ ps_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Service status check
  shell: "service {{ item }} status"
  with_items:
  - "{{ maxscale_service }}"
  register: service_list
  ignore_errors: true

- name: Print services status
  debug:
    msg: "{{ item }}"
  with_items:
  - "{{ service_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Monitors maxscale
  shell: "{{ maxscale_bin_path }}/maxctrl list monitors"
  register: monitors_result
  ignore_errors: true

- name: Print monitors result
  debug:
    msg: "{{ monitors_result.stdout_lines }}"

- name: Servers maxscale
  shell: "{{ maxscale_bin_path }}/maxctrl list servers"
  register: servers_result
  ignore_errors: true

- name: Print servers result
  debug:
    msg: "{{ servers_result.stdout_lines }}"
