---
- name: Port check
  shell: /bin/netstat -tnlp | grep ":{{ item }} "
  register: port_list
  ignore_errors: true
  with_items:
  - "{{ harbor_port }}"

- name: Print ports
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ port_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Process check
  shell: ps aux | grep -v "grep" | grep {{ item }}
  with_items:
  - "{{ harbor_process }}"
  register: ps_list
  ignore_errors: true

- name: Print process
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
  - "{{ ps_list.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Container check
  shell: "{{ container_ctl }} ps -a"
  register: container_list
  ignore_errors: true

- name: Print containers 
  debug:
    msg: "{{ container_list.stdout_lines }}"
